# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /home/pranav/Downloads/project_2_LAB5new/project_2_LAB5/project_2.cache/wt [current_project]
set_property parent.project_path /home/pranav/Downloads/project_2_LAB5new/project_2_LAB5/project_2.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property ip_output_repo /home/pranav/Downloads/project_2_LAB5new/project_2_LAB5/project_2.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_mem /home/pranav/Downloads/project_2_LAB5new/project_2_LAB5/project_2.srcs/sources_1/new/rams_init_file.data
read_vhdl -library xil_defaultlib {
  /home/pranav/Downloads/project_2_LAB5new/project_2_LAB5/project_2.srcs/sources_1/new/local_memory.vhd
  /home/pranav/Downloads/project_2_LAB5new/project_2_LAB5/project_2.srcs/sources_1/new/Shifter.vhd
  /home/pranav/Downloads/project_2_LAB5new/project_2_LAB5/project_2.srcs/sources_1/new/processor_memory_path.vhd
  /home/pranav/Downloads/project_2_LAB5new/project_2_LAB5/project_2.srcs/sources_1/new/multiplier.vhd
  /home/pranav/Downloads/project_2_LAB5new/project_2_LAB5/project_2.srcs/sources_1/new/ALU.vhd
  /home/pranav/Downloads/project_2_LAB5new/project_2_LAB5/project_2.srcs/sources_1/new/registerFile.vhd
  /home/pranav/Downloads/project_2_LAB5new/project_2_LAB5/project_2.srcs/sources_1/new/MainCtrl.vhd
  /home/pranav/Downloads/project_2_LAB5new/project_2_LAB5/project_2.srcs/sources_1/new/Bctrl.vhd
  /home/pranav/Downloads/project_2_LAB5new/project_2_LAB5/project_2.srcs/sources_1/new/Actrl.vhd
  /home/pranav/Downloads/project_2_LAB5new/project_2_LAB5/project_2.srcs/sources_1/new/Datapath.vhd
  /home/pranav/Downloads/project_2_LAB5new/project_2_LAB5/project_2.srcs/sources_1/new/master.vhd
  /home/pranav/Downloads/project_2_LAB5new/project_2_LAB5/project_2.srcs/sources_1/new/board.vhd
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc /home/pranav/Downloads/project_2_LAB5new/project_2_LAB5/project_2.srcs/constrs_1/new/xdc_file.xdc
set_property used_in_implementation false [get_files /home/pranav/Downloads/project_2_LAB5new/project_2_LAB5/project_2.srcs/constrs_1/new/xdc_file.xdc]


synth_design -top board -part xc7a35tcpg236-1


write_checkpoint -force -noxdef board.dcp

catch { report_utilization -file board_utilization_synth.rpt -pb board_utilization_synth.pb }
